# @generated by tools/bazel/generate_build_files.py; do not edit.
WORKSPACE_COMPILE_TARGETS = [
    "//crates/hirsel-client-core:client_flow__test",
    "//crates/hirsel-client-core:hirsel-client-core",
    "//crates/hirsel-client-core:hirsel-client-core__unit_test",
    "//crates/hirsel-client-ffi:hirsel-client-ffi",
    "//crates/hirsel-client-ffi:hirsel-client-ffi__unit_test",
    "//crates/hirsel-drivers:hirsel-drivers",
    "//crates/hirsel-drivers:hirsel-drivers__unit_test",
    "//crates/hirsel-host:build_script",
    "//crates/hirsel-host:hirsel-host",
    "//crates/hirsel-host:hirsel-host__bin",
    "//crates/hirsel-host:hirsel-host__bin__unit_test",
    "//crates/hirsel-host:hirsel-host__unit_test",
    "//crates/hirsel-host:hirsel-pair__bin",
    "//crates/hirsel-host:hirsel-pair__bin__unit_test",
    "//crates/hirsel-host:nested_runtime__test",
    "//crates/hirsel-plugin-api:hirsel-plugin-api",
    "//crates/hirsel-plugin-api:hirsel-plugin-api__unit_test",
    "//crates/hirsel-plugins:hirsel-plugins",
    "//crates/hirsel-plugins:hirsel-plugins__unit_test",
    "//crates/hirsel-proto:hirsel-proto",
    "//crates/hirsel-proto:hirsel-proto__unit_test",
]

WORKSPACE_CLIPPY_TARGETS = [
    "//crates/hirsel-client-core:client_flow__test",
    "//crates/hirsel-client-core:hirsel-client-core",
    "//crates/hirsel-client-core:hirsel-client-core__unit_test",
    "//crates/hirsel-client-ffi:hirsel-client-ffi",
    "//crates/hirsel-client-ffi:hirsel-client-ffi__unit_test",
    "//crates/hirsel-drivers:hirsel-drivers",
    "//crates/hirsel-drivers:hirsel-drivers__unit_test",
    "//crates/hirsel-host:hirsel-host",
    "//crates/hirsel-host:hirsel-host__bin",
    "//crates/hirsel-host:hirsel-host__bin__unit_test",
    "//crates/hirsel-host:hirsel-host__unit_test",
    "//crates/hirsel-host:hirsel-pair__bin",
    "//crates/hirsel-host:hirsel-pair__bin__unit_test",
    "//crates/hirsel-host:nested_runtime__test",
    "//crates/hirsel-plugin-api:hirsel-plugin-api",
    "//crates/hirsel-plugin-api:hirsel-plugin-api__unit_test",
    "//crates/hirsel-plugins:hirsel-plugins",
    "//crates/hirsel-plugins:hirsel-plugins__unit_test",
    "//crates/hirsel-proto:hirsel-proto",
    "//crates/hirsel-proto:hirsel-proto__unit_test",
]

WORKSPACE_DOC_TARGETS = [
    "//crates/hirsel-client-core:hirsel-client-core__doc",
    "//crates/hirsel-client-ffi:hirsel-client-ffi__doc",
    "//crates/hirsel-drivers:hirsel-drivers__doc",
    "//crates/hirsel-host:hirsel-host__doc",
    "//crates/hirsel-plugin-api:hirsel-plugin-api__doc",
    "//crates/hirsel-plugins:hirsel-plugins__doc",
    "//crates/hirsel-proto:hirsel-proto__doc",
]

WORKSPACE_RUST_SOURCE_TARGETS = [
    "//crates/hirsel-client-core:rust_sources",
    "//crates/hirsel-client-ffi:rust_sources",
    "//crates/hirsel-drivers:rust_sources",
    "//crates/hirsel-host:rust_sources",
    "//crates/hirsel-plugin-api:rust_sources",
    "//crates/hirsel-plugins:rust_sources",
    "//crates/hirsel-proto:rust_sources",
]

WORKSPACE_BAZEL_TEST_TARGETS = [
    "//crates/hirsel-client-core:client_flow__test",
    "//crates/hirsel-client-core:hirsel-client-core__unit_test",
    "//crates/hirsel-client-ffi:hirsel-client-ffi__unit_test",
    "//crates/hirsel-drivers:hirsel-drivers__unit_test",
    "//crates/hirsel-host:hirsel-host__bin__unit_test",
    "//crates/hirsel-host:hirsel-host__unit_test",
    "//crates/hirsel-host:hirsel-pair__bin__unit_test",
    "//crates/hirsel-plugin-api:hirsel-plugin-api__unit_test",
    "//crates/hirsel-plugins:hirsel-plugins__unit_test",
    "//crates/hirsel-proto:hirsel-proto__unit_test",
]

WORKSPACE_CARGO_TEST_TARGETS = [
    "//crates/hirsel-host:nested_runtime__test",
]

WORKSPACE_TEST_TARGETS = [
    "//crates/hirsel-client-core:client_flow__test",
    "//crates/hirsel-client-core:hirsel-client-core__unit_test",
    "//crates/hirsel-client-ffi:hirsel-client-ffi__unit_test",
    "//crates/hirsel-drivers:hirsel-drivers__unit_test",
    "//crates/hirsel-host:hirsel-host__bin__unit_test",
    "//crates/hirsel-host:hirsel-host__unit_test",
    "//crates/hirsel-host:hirsel-pair__bin__unit_test",
    "//crates/hirsel-host:nested_runtime__test",
    "//crates/hirsel-plugin-api:hirsel-plugin-api__unit_test",
    "//crates/hirsel-plugins:hirsel-plugins__unit_test",
    "//crates/hirsel-proto:hirsel-proto__unit_test",
]
