//! Generated aggregator: the one place that names every installed plugin.
//!
//! `Cargo.toml` and `src/registry.rs` in this crate are GENERATED by
//! `scripts/sync-plugins.sh` from the folders under `plugins/`. Both are
//! checked in, and CI re-runs the script and fails if the tree differs — so a
//! plugin folder that was dropped in but never synced is caught rather than
//! silently ignored. Edit the generator, never the generated files.

mod registry;

pub use registry::all;
