//! GENERATED by scripts/sync-plugins.sh — do not edit.
//!
//! One entry per folder under `plugins/`. Version and folder come from
//! the plugin's own Cargo.toml, because `env!` in the API crate would
//! expand against the API crate rather than the plugin.

use hirsel_plugin_api::PluginRegistration;

/// Every installed plugin, in folder order.
pub fn all() -> Vec<PluginRegistration> {
    Vec::new()
}
