import { escapeHtml as text, isMarkdownArtifact, markdownDocumentBody, MARKDOWN_STYLE } from "./markdown";
import runtime from "virtual:artifact-runtime";
import { ARTIFACT_DISMISS_MESSAGE, type Artifact } from "./types";

export const ARTIFACT_SANDBOX = "allow-scripts";
// No same-origin permission, credentials, tool handles, or host capabilities.
export const ARTIFACT_CSP = "default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data: blob:; font-src data:; connect-src 'none'; frame-src 'none'; worker-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'; media-src data: blob:";
function script(source: string): string { return source.replace(/<\/script/gi, "<\\/script"); }
const errorBoundary = `const dismiss = () => parent.postMessage('${ARTIFACT_DISMISS_MESSAGE}', '*'); addEventListener('keydown', event => { if(event.key === 'Escape' && !event.defaultPrevented) { event.preventDefault(); dismiss(); } }); document.getElementById('artifact-close').addEventListener('click', dismiss); const showError = error => { const output = document.getElementById('artifact-error'); output.hidden=false; document.getElementById('artifact-details').textContent=String(error?.message ?? error).slice(0,1000); const root = document.getElementById('artifact-root'); if(root) root.hidden=true; }; addEventListener('error', e => showError(e.error ?? e.message)); addEventListener('unhandledrejection', e => showError(e.reason));`;
export function artifactDocument(artifact: Artifact, compiled?: string): string {
  const head = `<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="${ARTIFACT_CSP}"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${text(artifact.title)}</title><style>body{margin:0;padding:20px;font:16px/1.5 system-ui,sans-serif;color:#202124;background:#fff;overflow-wrap:anywhere}*{box-sizing:border-box}pre{white-space:pre-wrap}button,input,select,textarea{font:inherit}#artifact-error{padding:4px;max-width:65ch}#artifact-error p{margin:0 0 16px}#artifact-error button{min-height:44px;padding:8px 16px;border:0;border-radius:8px;color:inherit;background:#e8eeee;cursor:pointer}#artifact-error button:focus-visible,#artifact-error summary:focus-visible{outline:2px solid #247463;outline-offset:3px}#artifact-error details{margin-top:12px;color:#4b5563}#artifact-error summary{cursor:pointer;min-height:44px;padding:10px 0}#artifact-error pre{font-size:13px;max-height:16rem;overflow:auto}${MARKDOWN_STYLE}</style></head><body><section id="artifact-error" role="alert" hidden><p><strong>This artifact stopped working.</strong></p><p>Close the preview and ask Hirsel to repair artifact #${artifact.id}, “${text(artifact.title)}”. Your conversation and draft are kept.</p><button id="artifact-close" type="button">Close preview</button><details><summary>Technical details</summary><pre id="artifact-details"></pre></details></section>`;
  if (artifact.kind === "file") return `${head}<script>${errorBoundary}</script>${isMarkdownArtifact(artifact) ? markdownDocumentBody(artifact.content) : `<pre>${text(artifact.content)}</pre>`}</body></html>`;
  if (artifact.kind === "html") return `${head}<script>${errorBoundary}</script>${artifact.content}</body></html>`;
  if (!compiled) throw new Error("Solid artifact has not been compiled.");
  const execute = `${runtime}\n${errorBoundary}\ntry { const exports = {}; const module = { exports }; const require = name => { const value=globalThis.__artifactModules[name]; if(!value) throw new Error('Only solid-js and @solidjs/web imports are available.'); return value; };\n${compiled}\nif(typeof module.exports.default !== 'function') throw new Error('Export a default Solid component.'); globalThis.__artifactModules['@solidjs/web'].render(() => module.exports.default({}), document.getElementById('artifact-root')); } catch(error) { showError(error); }`;
  return `${head}<div id="artifact-root"></div><script>${script(execute)}</script></body></html>`;
}
