#!/usr/bin/env bash
set -euo pipefail

# Regenerate the plugin aggregator crate from the folders under `plugins/`.
#
# Installing a plugin is: drop `plugins/<id>/` in, run this script, rebuild.
# The two generated files (`crates/hirsel-plugins/Cargo.toml` and
# `crates/hirsel-plugins/src/registry.rs`) are checked in; CI re-runs this
# script and fails if the tree differs, so an unsynced folder is caught.
#
# Each plugin crate must export `pub fn plugin() -> Box<dyn Plugin>`.

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

plugins_dir="plugins"
aggregator_dir="crates/hirsel-plugins"
cargo_out="$aggregator_dir/Cargo.toml"
registry_out="$aggregator_dir/src/registry.rs"

mkdir -p "$aggregator_dir/src"

# `name = "..."` / `version = "..."` from the [package] table. Plugin manifests
# are plain enough that the first match of each key is the package's own.
manifest_field() {
  local manifest="$1" field="$2"
  sed -n "s/^${field}[[:space:]]*=[[:space:]]*\"\([^\"]*\)\".*/\1/p" "$manifest" | head -1
}

ids=()
names=()
versions=()

if [[ -d "$plugins_dir" ]]; then
  while IFS= read -r manifest; do
    dir="$(dirname "$manifest")"
    id="$(basename "$dir")"
    name="$(manifest_field "$manifest" name)"
    version="$(manifest_field "$manifest" version)"
    if [[ -z "$name" ]]; then
      echo "plugins/$id/Cargo.toml has no package name" >&2
      exit 1
    fi
    if [[ -z "$version" ]]; then
      echo "plugins/$id/Cargo.toml has no package version (workspace inheritance is not supported for plugins)" >&2
      exit 1
    fi
    if ! [[ "$id" =~ ^[a-z][a-z0-9]*(-[a-z0-9]+)*$ ]]; then
      echo "plugin folder '$id' is not lowercase kebab-case" >&2
      exit 1
    fi
    ids+=("$id")
    names+=("$name")
    versions+=("$version")
  done < <(find "$plugins_dir" -mindepth 2 -maxdepth 2 -name Cargo.toml | sort)
fi

{
  echo "# GENERATED by scripts/sync-plugins.sh — do not edit."
  echo "#"
  echo "# Regenerate after adding or removing a folder under plugins/."
  echo "[package]"
  echo 'name = "hirsel-plugins"'
  echo 'version = "0.1.0"'
  echo "edition.workspace = true"
  echo "license.workspace = true"
  echo "rust-version.workspace = true"
  echo
  echo "[dependencies]"
  echo "hirsel-plugin-api.workspace = true"
  for index in "${!ids[@]}"; do
    printf '%s = { path = "../../%s/%s" }\n' "${names[$index]}" "$plugins_dir" "${ids[$index]}"
  done
} > "$cargo_out"

{
  echo "//! GENERATED by scripts/sync-plugins.sh — do not edit."
  echo "//!"
  echo "//! One entry per folder under \`plugins/\`. Version and folder come from"
  echo "//! the plugin's own Cargo.toml, because \`env!\` in the API crate would"
  echo "//! expand against the API crate rather than the plugin."
  echo
  echo "use hirsel_plugin_api::PluginRegistration;"
  echo
  echo "/// Every installed plugin, in folder order."
  echo "pub fn all() -> Vec<PluginRegistration> {"
  if ((${#ids[@]} == 0)); then
    echo "    Vec::new()"
  else
    echo "    vec!["
    for index in "${!ids[@]}"; do
      crate_ident="${names[$index]//-/_}"
      printf '        PluginRegistration::new(%s::plugin(), "%s", "%s/%s"),\n' \
        "$crate_ident" "${versions[$index]}" "$plugins_dir" "${ids[$index]}"
    done
    echo "    ]"
  fi
  echo "}"
} > "$registry_out"

# Keep the generated file fmt-stable so `cargo fmt --check` and the
# check-plugins-synced gate agree on one canonical form.
if command -v rustfmt >/dev/null 2>&1; then
  rustfmt --edition 2021 "$registry_out"
fi

echo "synced ${#ids[@]} plugin(s) into $aggregator_dir"
