#!/usr/bin/env node
// Generates prompts/openui-library.md from the component schemas in
// app/src/openui/schema.ts. The signatures an agent reads are derived from the
// same objects the renderer uses, so the prompt cannot drift from the library.
//
//   node app/scripts/openui-prompt.mjs          write the file
//   node app/scripts/openui-prompt.mjs --check  fail if it is stale
import { generateSystemPrompt } from "@openuidev/lang-core";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { promptSpec } from "../src/openui/schema.ts";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const target = join(repoRoot, "prompts", "openui-library.md");

const LEAD = `## OpenUI component library

Generated from \`app/src/openui/schema.ts\` by \`node app/scripts/openui-prompt.mjs\`.
Do not edit this file by hand.

An \`openui\` artifact's content is one openui-lang program written against the
component library below. Hirsel draws it natively with its own design tokens, so
it is on-brand without being asked, it renders while it is still being written,
and a line it cannot parse is dropped instead of breaking the page.

Prefer \`openui\` for anything the Owner reads or operates: dashboards, metric
bands, tables, comparisons, checklists, forms, surveys and suggested replies.
Prefer \`solid\` only for a custom visualisation or interaction this vocabulary
cannot express, \`markdown\` for a document, and \`html\` for a self-contained page
that must stay exactly as authored.

A Button or FollowUp sends an ordinary Owner message back to the artifact's
Thread: the label the person saw, then a fenced JSON block with the artifact id,
the action name, its params and the form state. Read that block to learn what
was chosen, and edit the artifact with \`artifacts_edit\` — one
\`identifier = Component(...)\` line at a time — to answer.

`;

const PREAMBLE = `The content of an \`openui\` artifact is one openui-lang program: nothing else, no
markdown fence, no commentary. Everything the Owner should see must be reachable
from \`root\`.`;

const RULES = [
  "Keep one statement per line and give each a short, descriptive identifier — an edit replaces exactly one line.",
  "Use the components below and nothing else. An unknown component name is dropped silently.",
  "Every input needs a unique `name`, and inputs that are answered together belong in one Form.",
  "Numbers in a Chart are numbers, not strings; a Table's cells are strings.",
];

const EXAMPLE = `root = Stack([band, table, ask])
band = Stack([openRate, replies], "row", "md")
openRate = Metric("Open rate", "38%", "+4pt", "up")
replies = Metric("Replies", "112", "-9", "down")
table = Section("By segment", [segments])
segments = Table(["Segment", "Sent", "Opened"], [["Trial", "820", "310"], ["Paid", "1,240", "470"]])
ask = Form("narrow", [segment], [apply])
segment = Select("segment", ["Trial", "Paid", "Churned"], "Segment", "All segments")
apply = Button("Apply filter", "narrow", "primary")`;

const generated = LEAD + generateSystemPrompt({
  library: promptSpec(),
  promptOptions: { preamble: PREAMBLE, additionalRules: RULES, examples: [EXAMPLE] },
}).trimEnd() + "\n";

if (process.argv.includes("--check")) {
  let current = "";
  try { current = readFileSync(target, "utf8"); } catch { current = ""; }
  if (current !== generated) {
    console.error("prompts/openui-library.md is stale. Run: node app/scripts/openui-prompt.mjs");
    process.exit(1);
  }
  console.log("prompts/openui-library.md is current.");
} else {
  writeFileSync(target, generated);
  console.log(`Wrote ${target}`);
}
